---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tomcat9
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tomcat9
  namespace: demo-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-tomcat9
...
